import Foundation
import Prelude

public extension CPU {
    public mutating func step() {
        let opcode: UInt8 = memory.read(PC)

        switch opcode {
        case 0x00: (BRK, 7, 0) |> implied
        case 0x01: (ORA, 6, 0) |> indexedIndirect
        case 0x05: (ORA, 3, 0) |> zeroPage
        case 0x06: (ASL, 5, 0) |> zeroPage
        case 0x08: (PHP, 3, 0) |> implied
        case 0x09: (ORA, 2, 0) |> immediate
        case 0x0A: (ASL, 2, 0) |> accumulator
        case 0x0D: (ORA, 4, 0) |> absolute
        case 0x0E: (ASL, 6, 0) |> absolute
        case 0x10: (BPL, 2, 1) |> relative
        case 0x11: (ORA, 5, 1) |> indirectIndexed
        case 0x15: (ORA, 4, 0) |> zeroPageX
        case 0x16: (ASL, 6, 0) |> zeroPageX
        case 0x18: (CLC, 2, 0) |> implied
        case 0x19: (ORA, 4, 1) |> absoluteY
        case 0x1D: (ORA, 4, 1) |> absoluteX
        case 0x1E: (ASL, 7, 0) |> absoluteX
        case 0x20: (JSR, 6, 0) |> absolute
        case 0x21: (AND, 6, 0) |> indexedIndirect
        case 0x24: (BIT, 3, 0) |> zeroPage
        case 0x25: (AND, 3, 0) |> zeroPage
        case 0x26: (ROL, 5, 0) |> zeroPage
        case 0x28: (PLP, 4, 0) |> implied
        case 0x29: (AND, 2, 0) |> immediate
        case 0x2A: (ROL, 2, 0) |> accumulator
        case 0x2C: (BIT, 4, 0) |> absolute
        case 0x2D: (AND, 4, 0) |> absolute
        case 0x2E: (ROL, 6, 0) |> absolute
        case 0x30: (BMI, 2, 1) |> relative
        case 0x31: (AND, 5, 1) |> indirectIndexed
        case 0x35: (AND, 4, 0) |> zeroPageX
        case 0x36: (ROL, 6, 0) |> zeroPageX
        case 0x38: (SEC, 2, 0) |> implied
        case 0x39: (AND, 4, 1) |> absoluteY
        case 0x3D: (AND, 4, 1) |> absoluteX
        case 0x3E: (ROL, 7, 0) |> absoluteX
        case 0x40: (RTI, 6, 0) |> implied
        case 0x41: (EOR, 6, 0) |> indexedIndirect
        case 0x45: (EOR, 3, 0) |> zeroPage
        case 0x46: (LSR, 5, 0) |> zeroPage
        case 0x48: (PHA, 3, 0) |> implied
        case 0x49: (EOR, 2, 0) |> immediate
        case 0x4A: (LSR, 2, 0) |> accumulator
        case 0x4C: (JMP, 3, 0) |> absolute
        case 0x4D: (EOR, 4, 0) |> absolute
        case 0x4E: (LSR, 6, 0) |> absolute
        case 0x50: (BVC, 2, 1) |> relative
        case 0x51: (EOR, 5, 1) |> indirectIndexed
        case 0x55: (EOR, 4, 0) |> zeroPageX
        case 0x56: (LSR, 6, 0) |> zeroPageX
        case 0x58: (CLI, 2, 0) |> implied
        case 0x59: (EOR, 4, 1) |> absoluteY
        case 0x5D: (EOR, 4, 1) |> absoluteX
        case 0x5E: (LSR, 7, 0) |> absoluteX
        case 0x60: (RTS, 6, 0) |> implied
        case 0x61: (ADC, 6, 0) |> indexedIndirect
        case 0x65: (ADC, 3, 0) |> zeroPage
        case 0x66: (ROR, 5, 0) |> zeroPage
        case 0x68: (PLA, 4, 0) |> implied
        case 0x69: (ADC, 2, 0) |> immediate
        case 0x6A: (ROR, 2, 0) |> accumulator
        case 0x6C: (JMP, 5, 0) |> indirect
        case 0x6D: (ADC, 4, 0) |> absolute
        case 0x6E: (ROR, 6, 0) |> absolute
        case 0x70: (BVS, 2, 1) |> relative
        case 0x71: (ADC, 5, 1) |> indirectIndexed
        case 0x75: (ADC, 4, 0) |> zeroPageX
        case 0x76: (ROR, 6, 0) |> zeroPageX
        case 0x78: (SEI, 2, 0) |> implied
        case 0x79: (ADC, 4, 1) |> absoluteY
        case 0x7D: (ADC, 4, 1) |> absoluteX
        case 0x7E: (ROR, 7, 0) |> absoluteX
        case 0x81: (STA, 6, 0) |> indexedIndirect
        case 0x84: (STY, 3, 0) |> zeroPage
        case 0x85: (STA, 3, 0) |> zeroPage
        case 0x86: (STX, 3, 0) |> zeroPage
        case 0x88: (DEY, 2, 0) |> implied
        case 0x8A: (TXA, 2, 0) |> implied
        case 0x8C: (STY, 4, 0) |> absolute
        case 0x8D: (STA, 4, 0) |> absolute
        case 0x8E: (STX, 4, 0) |> absolute
        case 0x90: (BCC, 2, 1) |> relative
        case 0x91: (STA, 6, 0) |> indirectIndexed
        case 0x94: (STY, 4, 0) |> zeroPageX
        case 0x95: (STA, 4, 0) |> zeroPageX
        case 0x96: (STX, 4, 0) |> zeroPageY
        case 0x98: (TYA, 2, 0) |> implied
        case 0x99: (STA, 5, 0) |> absoluteY
        case 0x9A: (TXS, 2, 0) |> implied
        case 0x9D: (STA, 5, 0) |> absoluteX
        case 0xA0: (LDY, 2, 0) |> immediate
        case 0xA1: (LDA, 6, 0) |> indexedIndirect
        case 0xA2: (LDX, 2, 0) |> immediate
        case 0xA4: (LDY, 3, 0) |> zeroPage
        case 0xA5: (LDA, 3, 0) |> zeroPage
        case 0xA6: (LDX, 3, 0) |> zeroPage
        case 0xA8: (TAY, 2, 0) |> implied
        case 0xA9: (LDA, 2, 0) |> immediate
        case 0xAA: (TAX, 2, 0) |> implied
        case 0xAC: (LDY, 4, 0) |> absolute
        case 0xAD: (LDA, 4, 0) |> absolute
        case 0xAE: (LDX, 4, 0) |> absolute
        case 0xB0: (BCS, 2, 1) |> relative
        case 0xB1: (LDA, 5, 1) |> indirectIndexed
        case 0xB4: (LDY, 4, 0) |> zeroPageX
        case 0xB5: (LDA, 4, 0) |> zeroPageX
        case 0xB6: (LDX, 4, 0) |> zeroPageY
        case 0xB8: (CLV, 2, 0) |> implied
        case 0xB9: (LDA, 4, 1) |> absoluteY
        case 0xBA: (TSX, 2, 0) |> implied
        case 0xBC: (LDY, 4, 1) |> absoluteX
        case 0xBD: (LDA, 4, 1) |> absoluteX
        case 0xBE: (LDX, 4, 1) |> absoluteY
        case 0xC0: (CPY, 2, 0) |> immediate
        case 0xC1: (CMP, 6, 0) |> indexedIndirect
        case 0xC4: (CPY, 3, 0) |> zeroPage
        case 0xC5: (CMP, 3, 0) |> zeroPage
        case 0xC6: (DEC, 5, 0) |> zeroPage
        case 0xC8: (INY, 2, 0) |> implied
        case 0xC9: (CMP, 2, 0) |> immediate
        case 0xCA: (DEX, 2, 0) |> implied
        case 0xCC: (CPY, 4, 0) |> absolute
        case 0xCD: (CMP, 4, 0) |> absolute
        case 0xCE: (DEC, 6, 0) |> absolute
        case 0xD0: (BNE, 2, 1) |> relative
        case 0xD1: (CMP, 5, 1) |> indirectIndexed
        case 0xD5: (CMP, 4, 0) |> zeroPageX
        case 0xD6: (DEC, 6, 0) |> zeroPageX
        case 0xD8: (CLD, 2, 0) |> implied
        case 0xD9: (CMP, 4, 1) |> absoluteY
        case 0xDD: (CMP, 4, 1) |> absoluteX
        case 0xDE: (DEC, 7, 0) |> absoluteX
        case 0xE0: (CPX, 2, 0) |> immediate
        case 0xE1: (SBC, 6, 0) |> indexedIndirect
        case 0xE4: (CPX, 3, 0) |> zeroPage
        case 0xE5: (SBC, 3, 0) |> zeroPage
        case 0xE6: (INC, 5, 0) |> zeroPage
        case 0xE8: (INX, 2, 0) |> implied
        case 0xE9: (SBC, 2, 0) |> immediate
        case 0xEB: (SBC, 2, 0) |> immediate
        case 0xEC: (CPX, 4, 0) |> absolute
        case 0xED: (SBC, 4, 0) |> absolute
        case 0xEE: (INC, 6, 0) |> absolute
        case 0xF0: (BEQ, 2, 1) |> relative
        case 0xF1: (SBC, 5, 1) |> indirectIndexed
        case 0xF5: (SBC, 4, 0) |> zeroPageX
        case 0xF6: (INC, 6, 0) |> zeroPageX
        case 0xF8: (SED, 2, 0) |> implied
        case 0xF9: (SBC, 4, 1) |> absoluteY
        case 0xFD: (SBC, 4, 1) |> absoluteX
        case 0xFE: (INC, 7, 0) |> absoluteX

        default:
            fatalError("Unknown opcode \(opcode)")
        }
    }
}
